// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.14.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RTwY7TMBD9lWjgWOLCcsoNBEIrcajgWPUwdSZZrxzbjJ2Fquq/o3GTNC1F2wMH9pTI",
	"fvPmzXvjPWjfBe/IpQjVHqJ+oA7z72dmz98oBu8iyUFgH4iToXxdY0L5pl0gqACZcQeHBXQUI7a5wCTq",
	"4gwTExvXCuiyKPZaU5xjt95bQgeHwwKYfvSGqYZqPSFPjRZHKZuJ1W8fSSehXXnXfhp0nqs3rvFXlF00",
	"y6i/ET9vzWumBip4pU4eq8FgNUmT6ROmPj4vZ8BdE0QS1ssMKRjXvqn/fUoCGwlqippNSMY7qODD6r5o",
	"MdFP3BWN5+Krj6nwTaEtmq6wW11E4iejRXYyyQrriNli22JLA/aEeyKOR/a35bJcymA+kMNgoIK7clne",
	"wQICpoc8mJKh5ef21zcsU1mqslQ8XKice7nr7OW6X4dLWzUZPq/7j7ZZgC2lP3OTLpB9ZZSj+xoq+EJp",
	"ZfL5OGXu/W65PPrrErnMhSFYo3OheoxCOBp+y3STP1neua7vx3VveltM2sSJ9zdpoF/YBUsnq9eb2QNd",
	"j/ZtZg+wQRtJrL5J/vkqXdH/EetCkqGYckqx7zrknTh+DE7OiGXFoVrvoWcLFSjZ7cPm8DsAAP//03kx",
	"LUMGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
